### ISSUE TITLE
Release 2.0 checklist

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#31]
- [x] Landing page at http://www.nps.gov/npmap/tools/symbol-library/
- [x] "Unfork" repository to address #29 
- [x] Finalize artwork for new symbols tagged with milestone 1.1
- [x] Revisit build script
- [ ] Write a "release" checklist
- [ ] Write and document a deploy script to push new versions out to http://www.nps.gov/lib/npmap-symbol-library/
- [x] Blog post
- [x] Tag release on GitHub
- [x] Tweet w/link to blog post
- [x] Email to MailChimp list
- [x] Email to internal nps-gis list
- [ ] Write a script to generate landing page HTML, CSS, and JavaScript
- [x] Track which version a symbol was released in somewhere in the symbol set JSON file and 
- [ ] Expose this on the landing page, as well
## Nice to have
- [ ] Write and publish documentation
- [ ] Create homepage feature

**Comment by nateirwin** [comment]
I think we can scratch the landing page from this cycle - unless we magically find the time to implement before the release is ready ;-)

**Comment by nateirwin** [comment]
And I'm happy to touch base about the deploy script sometime soon. We now have deploy scripts for Builder, NPMap.js, and our website, and they're really nice and fairly simple to write. We may also want to rethink the build script we're using.

I'm going to modify the checklist to reflect my thoughts.

**Comment by mtaylorlong** [comment]
@nate & @jakecoolidge: What's left to do on this checklist? I'm ready to tweet and mailchimp, so I'll check those off the list after the post is published.

**Comment by jakecoolidge** [comment]
Thanks, @mtaylorlong! @nateirwin is going to review a pull request I have going for the npmap website. Once that's firmed up, the blog and landing page will be ready to go live. I'll let you know when that happens so you can release the emails.

**Comment by jakecoolidge** [comment]
Closing as the word gets out on v2.0. Will create separate issues for unresolved items on checklist.
