### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/symbol-library#8]
- [ ] Landing page at http://www.nps.gov/npmap/tools/npmaki/
- [ ] Deploy script to push new versions out to http://www.nps.gov/lib/npmaki/
- [x] Version up, and tag version here in GitHub
- [x] Publish new version to NPM
- [x] Integration with NPMap.js
- [x] Integration with Builder
- [x] Integration with all versions of Park Tiles
- [ ] Blog post

**Comment by jakecoolidge** [comment]
I'm going to create a [new checklist](https://github.com/nationalparkservice/npmap-symbol-library/issues/31) for the next release. It will include unresolved items from this list.
